# 1. Data Loading

In this section, we load historical stock price data downloaded using the Yahoo Finance API.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

# Display settings
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/stock_data.csv")

df.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2015-01-02,24.192602,27.332500,27.860001,26.837500,27.847500,212818400
1,2015-01-05,23.511061,26.562500,27.162500,26.352501,27.072500,257142000
2,2015-01-06,23.513271,26.565001,26.857500,26.157499,26.635000,263188400
3,2015-01-07,23.842979,26.937500,27.049999,26.674999,26.799999,160423600
4,2015-01-08,24.759089,27.972500,28.037500,27.174999,27.307501,237458000

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2766 entries, 0 to 2765
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2766 non-null   str
 1   Adj Close  2766 non-null   float64
 2   Close      2766 non-null   float64
 3   High       2766 non-null   float64
 4   Low        2766 non-null   float64
 5   Open       2766 non-null   float64
 6   Volume     2766 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 178.4 KB

In [4]:
df.describe()

,Adj Close,Close,High,Low,Open,Volume
count,2766.000000,2766.000000,2766.000000,2766.000000,2766.000000,2.766000e+03
mean,106.127485,108.644931,109.721494,107.462519,108.546994,1.113994e+08
std,74.183370,73.856228,74.561122,73.072339,73.777601,6.804243e+07
min,20.565870,22.584999,22.917500,22.367500,22.500000,1.791060e+07
25%,36.583476,39.080626,39.460626,38.765626,39.160000,6.488962e+07
50%,88.307228,91.204998,92.407501,90.283749,91.176250,9.454380e+07
75%,168.334438,170.830006,172.634998,169.352497,170.955002,1.372937e+08
max,285.659271,286.190002,288.619995,283.299988,286.200012,6.488252e+08

In [5]:
df.isnull().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [6]:
df.shape

(2766, 7)

In [7]:
df.columns

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [8]:
print(df.columns)

Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [9]:
print(df.columns.tolist())

['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

In [10]:
df.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2015-01-02,24.192602,27.332500,27.860001,26.837500,27.847500,212818400
1,2015-01-05,23.511061,26.562500,27.162500,26.352501,27.072500,257142000
2,2015-01-06,23.513271,26.565001,26.857500,26.157499,26.635000,263188400
3,2015-01-07,23.842979,26.937500,27.049999,26.674999,26.799999,160423600
4,2015-01-08,24.759089,27.972500,28.037500,27.174999,27.307501,237458000

In [11]:
print(df.columns.tolist())

['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

In [12]:
print(df.index)

RangeIndex(start=0, stop=2766, step=1)

Step 2: Convert Date

In [13]:
df["Date"] = pd.to_datetime(df["Date"])
df.set_index("Date", inplace=True)

Step 3: Moving Averages

In [14]:
# Moving Averages
df["MA20"] = df["Close"].rolling(20).mean()
df["MA50"] = df["Close"].rolling(50).mean()
df["MA100"] = df["Close"].rolling(100).mean()
df["MA200"] = df["Close"].rolling(200).mean()

Step 4: Daily Return

In [15]:
df["Daily_Return"] = df["Close"].pct_change()

Step 5: Volatility

In [16]:
df["Volatility"] = df["Daily_Return"].rolling(20).std()

Step 6: RSI

In [17]:
from ta.momentum import RSIIndicator

df["RSI"] = RSIIndicator(df["Close"]).rsi()

Step 7: MACD

In [18]:
from ta.trend import MACD

macd = MACD(df["Close"])

df["MACD"] = macd.macd()
df["MACD_Signal"] = macd.macd_signal()

Step 8: Bollinger Bands

In [19]:
from ta.volatility import BollingerBands

bb = BollingerBands(df["Close"])

df["BB_High"] = bb.bollinger_hband()
df["BB_Low"] = bb.bollinger_lband()

Step 9: Remove Missing Values

In [20]:
df.dropna(inplace=True)

Step 10: Save New Dataset

In [21]:
df.to_csv("../data/processed_stock_data.csv")

Step 11: Check Dataset

In [22]:
df.head()

,Adj Close,Close,High,Low,Open,Volume,MA20,MA50,MA100,MA200,Daily_Return,Volatility,RSI,MACD,MACD_Signal,BB_High,BB_Low
Date,,,,,,,,,,,,,,,,,
2015-10-16,24.883129,27.760000,28.0000,27.632500,27.945000,156930400,27.942375,28.08690,29.780450,30.332337,-0.007331,0.013303,47.247909,-0.155139,-0.182025,28.858909,27.025841
2015-10-19,25.037750,27.932501,27.9375,27.527500,27.700001,119036800,27.898875,28.06795,29.730325,30.335337,0.006214,0.012851,49.281038,-0.135251,-0.172670,28.726233,27.071517
2015-10-20,25.494900,28.442499,28.5425,27.705000,27.834999,195871200,27.903500,28.03820,29.689050,30.344737,0.018258,0.013110,54.824615,-0.077445,-0.153625,28.741855,27.065145
2015-10-21,25.492664,28.440001,28.8950,28.424999,28.500000,167180800,27.896500,28.03955,29.647100,30.354112,-0.000088,0.012978,54.793017,-0.031472,-0.129195,28.714228,27.078772
2015-10-22,25.882580,28.875000,28.8750,28.525000,28.582500,166616400,27.902750,28.04085,29.610950,30.363800,0.015295,0.013372,59.201625,0.039606,-0.095434,28.747926,27.057574